### ISSUE TITLE
Graph height not dynamically (re/de)scaling

### ISSUE THREAD

**Issue by Ramontique** [GameTechDev/PresentMon#145] opened 2023-08-18 20:18 UTC
The height of the graphs doesn't dynamically (re)scale resulting in two lines almost on top of each other on the bottom of the graph:

https://i.imgur.com/HidEnXu.png

As you can see a lot of information is lost because of this.

**Comment by fdutheil** [comment] 2023-08-28 20:22
I can confirm, as soon as a game gets a high FPS value (like >1000FPS in a menu), the scale never recover, until I restart the PresentMon.

**Comment by planetchili** [comment] 2023-09-05 00:59
Thank you for reporting this issue. We are aware of it and working on a fix.
Duplicate of #162

**Comment by planetchili** [comment] 2023-09-05 00:59
Duplicate of #162

**Closed** 2023-09-05 01:02 UTC
Labels: duplicate, PresentMon-Overlay
