### ISSUE TITLE
PresentMon console app v1.9.0 has inconsistent process naming

### ISSUE THREAD

**Issue by DevTechProfile** [GameTechDev/PresentMon#157] opened 2023-08-25 19:09 UTC
We are starting the console app with the following input parameters from CapFrameX as a host.

![image](https://github.com/GameTechDev/PresentMon/assets/30285858/61e2c351-670b-4eed-be01-1f8dc3fd4ded)

The PresentMon console app only detects one game (per session). After closing this game and starting another one, our process list is empty. PM must be restarted to be able detect any other games. 

More precisely, if the game already runs before starting CapFrameX/PresentMon the detection works fine. "Detection" means that the process name is being included in the output data (Application column).

**Comment by DevTechProfile** [comment] 2023-08-25 19:20
``

**Comment by JeffersonMontgomery-Intel** [comment] 2023-08-25 22:18
I can't reproduce this so far.  I've started "PresentMon-1.9.0-x64.exe -stop_existing_session -no_csv -track_gpu" in an admin console, and then:

- started and stopped a graphics app multiple times
- started multiple graphics apps at the same time
- started multiple instances of the same app

and all seem to be picked up.

I've also tried starting graphics app before presentmon, and that is working too.

So, wondering what might be different.  What's OutputLevelofDetail and ExcludeProcesses?  Are there any other arguments?  Can you try the procedure above just with the console app (not through capframex)?

**Comment by DevTechProfile** [comment] 2023-08-26 08:21
Ok, I've found the root of problem. For some reasons you push the complete path of the app as the application name, see screenshot below. This is not the case when you restart PM while the same game just continues to run. 

We now have a workaround by separating path and app name. It's ok for us, but it can cause issues in other tools as well. Just want to let you know what we have observed so far. 

![image](https://github.com/GameTechDev/PresentMon/assets/30285858/7090429e-b47a-4332-935e-603195d85aaa)

**Comment by JeffersonMontgomery-Intel** [comment] 2023-08-28 18:58
I'm using a new technique for present detection that is "better", but yes the event can give this long process name. 

I didn't notice that it is inconsistent depending on how the app is running.  I'm glad you found a workaround, but I agree that is bad, and I'll fix that.

p.s., this also only happens when running as administrator.  I'm seeing:

| Run as admin | app/presentmon started first | Process name |
| - | - | - |
| Yes | app | short name |
| Yes | presentmon | long name |
| No | app | short name |
| No | presentmon | short name |

**Comment by JeffersonMontgomery-Intel** [comment] 2023-08-28 19:58
Should be fixed in [v1.9.1](https://github.com/GameTechDev/PresentMon/releases/tag/v1.9.1).

Thanks for reporting and helping to debug!

**Closed by JeffersonMontgomery-Intel** 2023-08-28 19:58 UTC
Labels: bug, PresentMon-ConsoleApplication
