### ISSUE TITLE
ETW Packets Lost

### ISSUE THREAD

**Issue by KyleStilkey** [GameTechDev/PresentMon#22] opened 2017-03-16 18:55 UTC
Hello, I keep getting the Error: Some ETW packets were lost. Collected data is unreliable.

What could be the cause of this issue?

**Comment by jdm3** [comment] 2017-03-16 21:47
You should also see something like "Lost # events, # buffers"?  In general, this happens when events are being created faster than they can be consumed.  Any events that happen while the buffers are full get dropped.

For you case in particular, I'm not sure as I haven't seen that happen myself.  Maybe lots of apps presenting, or one presenting very often?  You could try tweaking the buffer sizes by changing BufferSize (not Wnode.BufferSize), MinimumBuffers, and MaximumBuffers [here](https://github.com/GameTechDev/PresentMon/blob/master/TraceSession.cpp#L56) based on the documentation [here](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363784(v=vs.85).aspx) to see if that helps.

**Comment by MechWOLLIer** [comment] 2017-03-22 11:03
I've got the same issue ever and ever again in Battlefield 1 with DX12 (DX11 works fine in the game with PresentMon). But i don't see any lost, events or buffers.

**Comment by KyleStilkey** [comment] 2017-03-23 15:47
Yes, I wanted to report back that this is just with BF1 DX12. BF1 just received a new update the day I report this issue.

**Comment by yekrutdloc** [comment] 2017-09-04 07:33
Can confirm that it only happens with Battlefield 1 with DirectX 12 enabled. Has anybody found a fix for this yet?

**Comment by JeffersonMontgomery-Intel** [comment] 2019-08-20 23:40
I'm unable to reproduce this.  Assuming it's been fixed.

**Closed by JeffersonMontgomery-Intel** 2019-08-20 23:40 UTC
