### ISSUE TITLE
Windows 10 Creators Update

### ISSUE THREAD

**Issue by jarredwalton** [GameTechDev/PresentMon#25] opened 2017-04-19 19:42 UTC
Something seems to have changed quite a bit with Creators Update. PresentMon no longer collects any useful data from Doom Vulkan as an example, which was one of the few games where I needed it to work. The Hotkey option also doesn't seem to work at times (I tried it with Doom and didn't even get a results file for some reason).

**Comment by mat-lentils** [comment] 2017-04-19 20:34
Just wanted to let you know that I can reproduce this problem in Doom with Vulcan and OpenGL with the latest version (64 bit). DirectX 11 works like a charm. If I can help in any way, please let me know.

**Comment by mat-lentils** [comment] 2017-04-20 19:23
Just had some time on my hands and wanted to dive into this. I found a fix, although I have no clue if it's compatible with the overwhelming amount of possibilities to fill the present event. Here is a simple git diff as I didn't want to create a new branch for something that might be completely wrong as well. ;)

`$ git diff
diff --git a/PresentMonTraceConsumer.cpp b/PresentMonTraceConsumer.cpp
index d05f5e4..d148160 100644
--- a/PresentMonTraceConsumer.cpp
+++ b/PresentMonTraceConsumer.cpp
@@ -750,7 +750,7 @@ decltype(PMTraceConsumer::mPresentByThreadId.begin()) PMTraceConsumer::FindOrCre
     // Easy: we're on a thread that had some step in the present process
     auto eventIter = mPresentByThreadId.find(pEventRecord->EventHeader.ThreadId);
     if (eventIter != mPresentByThreadId.end()) {
-        if (eventIter->second->PresentMode != PresentMode::Unknown) {
+        if (eventIter->second->PresentMode != PresentMode::Unknown && eventIter->second->Runtime != Runtime::Other) {
             mPresentByThreadId.erase(eventIter);
         }
`

**Comment by jenatali** [comment] 2017-04-20 19:55
Thanks for digging in. I found where this issue was introduced: c52c02f9ea724c7e05cbc3ebf16d0f3c9a065ba5. The problem I was trying to fix was that the runtime provider stopped, so there was a present that was marked as coming from a runtime stuck in the by-thread map. It wouldn't get removed from that list until there was a stop event, so all future events were just finding this one instead of creating new ones like they should've.

This is actually a pretty good fix - remove the one event that got stuck. If it was just one stop event that got dropped, then the next present that completes will finish clearing the stuck one. If the runtime provider stopped (which can happen when dealing with ETW buffers of different sizes for different providers), then future presents won't be coming from a runtime so they won't expect an end event.

**Comment by mat-lentils** [comment] 2017-04-20 20:31
I might have found the solution for fullscreen as well. I am currently testing it in other games, but it works for DOOM.

[gitdiff.txt](https://github.com/GameTechDev/PresentMon/files/945396/gitdiff.txt)

**Comment by jenatali** [comment] 2017-04-20 20:36
Pretty sure that'd break D3D-based present paths.

**Comment by mat-lentils** [comment] 2017-04-20 22:54
I've tested a few games now in DX11, DX12, Vulkan and OpenGL in fullscreen and windowed and as far as I can tell, it works. I most certainly broke something with that code, but I can't wrap my head around it without any kind of documentation on the traces. Any help on this is very much appreciated, I would really like to fix this.

**Comment by mat-lentils** [comment] 2017-04-21 14:27
Couldn't get this out of my mind, so I researched a bit more. The typical event trace in DOOM in fullscreen mode looks like this:

> Skipped: OnDXGKrnlEvent 231 Provider: 2150548570
> Skipped: OnDXGKrnlEvent 169 Provider: 2150548570
> OnDXGKrnlEvent 178 Provider: 2150548570
> Skipped: OnDXGKrnlEvent 245 Provider: 2150548570
> Skipped: OnDXGKrnlEvent 230 Provider: 2150548570
> Skipped: OnDXGKrnlEvent 245 Provider: 2150548570
> Skipped: OnDXGKrnlEvent 230 Provider: 2150548570
> Skipped: OnDXGKrnlEvent 169 Provider: 2150548570
> OnDXGKrnlEvent 178 Provider: 2150548570
> Skipped: OnDXGKrnlEvent 245 Provider: 2150548570
> Skipped: OnDXGKrnlEvent 230 Provider: 2150548570
> Skipped: OnDXGKrnlEvent 231 Provider: 2150548570
> Skipped: OnDXGKrnlEvent 169 Provider: 2150548570
> OnDXGKrnlEvent 178 Provider: 2150548570
> Skipped: OnDXGKrnlEvent 245 Provider: 2150548570
> Skipped: OnDXGKrnlEvent 230 Provider: 2150548570
> Skipped: OnDXGKrnlEvent 245 Provider: 2150548570
> Skipped: OnDXGKrnlEvent 230 Provider: 2150548570
> Skipped: OnDXGKrnlEvent 244 Provider: 2150548570
> Skipped: OnDXGKrnlEvent 231 Provider: 2150548570
> Skipped: OnDXGKrnlEvent 169 Provider: 2150548570
> OnDXGKrnlEvent 178 Provider: 2150548570
> Skipped: OnDXGKrnlEvent 245 Provider: 2150548570
> Skipped: OnDXGKrnlEvent 230 Provider: 2150548570
> Skipped: OnDXGKrnlEvent 244 Provider: 2150548570
> Skipped: OnDXGKrnlEvent 231 Provider: 2150548570
> Skipped: OnDXGKrnlEvent 169 Provider: 2150548570
> OnDXGKrnlEvent 178 Provider: 2150548570
> Skipped: OnDXGKrnlEvent 245 Provider: 2150548570
> Skipped: OnDXGKrnlEvent 294 Provider: 2150548570
> Skipped: OnDXGKrnlEvent 245 Provider: 2150548570
> Skipped: OnDXGKrnlEvent 230 Provider: 2150548570
> OnDXGKrnlEvent 168 Provider: 2150548570
>  Process: DOOMx64vk.exe Provider: 2150548570 => Not found ... Check batched presents Event set with thread id: 2924
> OnDXGKrnlEvent 178 Provider: 2150548570
> OnDXGKrnlEvent 184 Provider: 2150548570
> Present: Window found

To complete a present and set the ready time, there currently has to be one of the following events:

- DxgKrnl_PresentHistoryDetailed (215)
- DxgKrnl_SubmitPresentHistory (171) <= this one happens in windowed and borderless mode (but only in borderless, when the game resolution is lower than the desktop resolution)
- DxgKrnl_PropagatePresentHistory (172)
- DxgKrnl_QueueComplete (180) <= this looks a lot like it should happen, but it doesn't (anymore)
- DxgKrnl_MMIOFlip (116)
- DxgKrnl_MMIOFlipMPO (259)

So the only events that are currently called are:

DxgKrnl_QueueSubmit (178) <= called multiple times before each present
DxgKrnl_Flip (168) <= called once and sets the present mode to Hardware_Legacy_Flip
DxgKrnl_Present (184) <= last event during a present, currently mostly used to get the hWnd

The question now is how to fix the missing completion of the present. My solution so far: Use the DxgKrnl_Present event and do what is necessary to complete the present. So added this after the Present Flag is checked for a redirected blit:

`		if (eventIter->second->PresentMode == PresentMode::Hardware_Legacy_Flip) {
			eventIter->second->ScreenTime = EventTime;
			eventIter->second->ReadyTime = EventTime;
			eventIter->second->PresentMode = PresentMode::Composed_Copy_CPU_GDI;
			eventIter->second->FinalState = PresentResult::Presented;
			CompletePresent(eventIter->second);
		}`

I've tested it and it seems to work so far, but I would like to check my solution from a theoretical basis as well. What do you think?

**Comment by jenatali** [comment] 2017-04-21 16:20
So in OpenGL at least, not sure about Vulcan, it's up to the driver to decide when the app should be fullscreen or borderless, which is why the behavior you're describing is different when you select borderless window at native resolution or not. The driver essentially figures out that it should go fullscreen instead.

When the app is windowed, I'd expect to see events following the Composed_Copy_CPU_GDI path. This is documented in PresentMonTraceConsumer.hpp:

    // Composed Copy with CPU GDI (a.k.a. Vista Blit),
    //   Runtime PresentStart -> Blt (by thread/process, for classification) -> SubmitPresentHistory (by thread, for token ptr, legacy blit token, and classification) ->
    //    PropagatePresentHsitory (by token ptr, for ready time) -> DWM FlipChain (by legacy blit token, for hWnd and marks hWnd active for composition) ->
    //    Follows the Windowed_Blit path for tracking to screen

It's possible it could be taking the GPU GDI path, which looks slightly different. All of the expected events are documented in this large comment block. When the app transitions to fullscreen, it will follow a completely different path, the hardware legacy flip path is what I'd expect.

The change you're suggesting above would pretend that a fullscreen flip was actually a windowed present, and that it completed as soon as it was submitted. Definitely not correct. I'm sorry I don't have more cycles to look at this right now, and I'm unfortunately going to be unavailable for most of next week, but I might be able to get a chance to investigate a full fix at the end of next week.

From the trace you pasted above, I see a bunch of rendering work that makes up a frame, and at the very end is a Flip, followed by a QueueSubmit, followed by a Present. Sometime much later, I'd expect to see a QueueComplete for the submit done between the flip and present.

**Comment by jenatali** [comment] 2017-04-21 21:19
I actually got a chance to look today before I took off. The problem you were seeing with Vulkan fullscreen presents was (probably) #24. I was checking with Talos Principle, not Doom, so you might be seeing something slightly different, but I think this was the problem.

**Comment by mat-lentils** [comment] 2017-04-21 23:15
Awesome! And it works like a charm, thank you! 👍 

I've tested it in serveral games and DOOM with OpenGL 4.5 still needs my first fix from above in FindOrCreatePresent()

if (eventIter->second->PresentMode != PresentMode::Unknown) {
			if (eventIter->second->Completed || eventIter->second->Runtime == Runtime::Other) {
				mPresentByThreadId.erase(eventIter);
			}
        }

**Comment by jenatali** [comment] 2017-04-21 23:20
My change replaced the PresentMode check with a Completed check. That wasn't enough?

**Comment by mat-lentils** [comment] 2017-04-22 12:17
I've rebenched today with fresh eyes and you are right, this change was enough and it works now with your fix.

I will bench a couple of games today for a hardware review and different setups and will get back to you. Thank you for your time!

**Closed** 2017-04-25 22:31 UTC

**Comment by jenatali** [comment] 2017-05-06 14:34
A couple of days after pushing the previous attempt at a fix for this, I was on a road trip and couldn't stop thinking about it. Eventually I convinced myself that the fix for Vulkan regressed the original reason I added the code into FindOrCreatePresent and came up with a different fix. #27 should fix the Vulkan issue plus the presents getting stuck issue.
