### ISSUE TITLE
GetData on pSwapChain EventDataDesc in HandleD3D9Event can hit the size_>sizeof(T) assert

### ISSUE THREAD

**Issue by aggieNick02** [GameTechDev/PresentMon#66] opened 2019-09-26 21:57 UTC
I'm not sure how widespread/easy this is to hit, but here is how I'm doing it. I verified the data being returned to _data is actually 8 bytes (the leading 4 bytes are non-zero).

1. Start hitman 2 running full screen by choosing "Play" at the launcher when starting it (you can get the base game for free on steam without any missions, and that is enough to hit the issue - it's at https://store.steampowered.com/app/863550/HITMAN_2/). Leave it at the menu where it says "PRESS [Enter] TO PLAY".
2. Once at the menu, alt-tab out of the game.
3. Start PresentMon.exe with:
`PresentMon.exe -process_name hitman2.exe`
4. Alt-tab back into the game
5. Wait a few seconds
6. Alt-tab back out of the game.
You'll get
`error: event's pSwapChain property had unexpected size (8>4)`

**Comment by jenatali** [comment] 2019-09-26 23:36
@JeffersonMontgomery-Intel looks like this is a regression from:
https://github.com/GameTechDev/PresentMon/commit/3d268139c6fb700fadf3a6bce88383263bdd0706#diff-2a3ead81d3e98a4aa32ade31b405100cR1023

This should be a pointer, not a uint32_t.

**Comment by JeffersonMontgomery-Intel** [comment] 2019-09-26 23:45
Yep, I'll fix asap.

**Comment by JeffersonMontgomery-Intel** [comment] 2019-09-27 00:48
Weird thing is that on my x64 system those event records are coming in with 4-byte POINTER and 32_BIT_HEADER flag.  Not sure how that happens (maybe the target app was 32-bit?) but it explains how this got by my testing.

Regardless the outer code should be asking for u64 and that gets converted without error whether the event is 4 or 8 bytes.  That's fixed now in master and [v1.5.2](https://github.com/GameTechDev/PresentMon/releases/tag/v1.5.2).

**Closed by JeffersonMontgomery-Intel** 2019-09-27 00:48 UTC

**Comment by aggieNick02** [comment] 2019-09-27 16:04
Thanks for fixing so fast. I dug a little more, and now that I understand the code base a little better, I can explain what's happening better.

Hitting the issue really had nothing to do with Hitman2. To hit it, you have to have a 64-bit app that happens to produce D3D9 events. I had hyper-v going on in the background, and it turns out that the process producing such events was c:\windows\system32\vmconnect.exe, which is for Hyper-V. Hitman2 leaving full-screen triggered vmconnect.exe to need to render.

A nice easy way to hit is to start Presentmon and then right click on a VM that's not running in Hyper-V and choose to connect.

Thanks again!

**Comment by JeffersonMontgomery-Intel** [comment] 2019-09-27 17:09
Shhh, you're killing my excuse to expense hitman to work :)  Just kidding -- thanks again for the great bug reports!

I think for whatever reason the thing creating d3d9 presents on my pc must have been a 32-bit app so I missed this one.  I'll find or build a 64-bit d3d9 app to explicitly add to my testing.
