### ISSUE TITLE
Compatibility with Windows 7, 8.1 and 32-bit operating systems.

### ISSUE THREAD

**Issue by EnzDducharme** [GameTechDev/PresentMon#30] opened 2017-05-17 17:14 UTC
I work doing performance analysis of D3D applications and one of the most valuable information is the frame time/frame rate. We have been using FRAPs for years now and I have been looking into substituting it with PresentMon completely. My only issue right now is that the application is 64-bit only and does not appear to record data on Windows 7 and 8.1.

Is support for these operating systems (and 32-bit OSes) planned at all? It would be extremely helpful for us it it were.

Thank you!

**Comment by jenatali** [comment] 2017-05-17 17:17
PresentMon can be built for 32-bit, it’s just that the official builds posted on GitHub are currently only 64-bit.

Does PresentMon work with the -simple command line on Win7/8.1?

**Comment by jdm3** [comment] 2017-05-17 17:20
32-bit exe added to release for convenience, see https://github.com/GameTechDev/PresentMon/releases/tag/v1.1.1

**Comment by EnzDducharme** [comment] 2017-05-17 17:33
Thanks a lot for the 32-bit exe! I'll give it a shot when I have a moment.

Just tried the -simple command line on Windows 7 and was able to fetch at least the MsBetweenPresents, which is the metric we mostly use. The issue seems to be with detected processes. All applications are labelled as "?error>" in the CSV and using the -process_name command line naturally doesn't work.

Although I haven't tested -simple on Windows 8.1, if I recall correctly, the same was true for the -process_name command line and PresentMon would otherwise log data without needing -simple.

It would help a lot if we were able to specify processes on Win7 and 8.1!

**Comment by jenatali** [comment] 2017-05-17 17:44
I just poked around a little bit, and it looks like the problem is we’re using [GetModuleFileNameEx](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683198(v=vs.85).aspx) instead of [QueryFullProcessImageName](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684919(v=vs.85).aspx). GetModuleFileNameEx documentation doesn't indicate it works if all we have is PROCESS_QUERY_LIMITED_INFORMATION access, but apparently this works on Win10. Documentation for QueryFullProcessImageName calls out it works for limited access.

I'll see if I can swap that out today, unless Jefferson gets to it before me.

**Comment by jdm3** [comment] 2017-05-17 17:46
Thanks for debug Jesse!  I will make the change.

**Comment by jdm3** [comment] 2017-05-17 19:17
Can you try [release 1.1.2](https://github.com/GameTechDev/PresentMon/releases/tag/v1.1.2) when you get a chance?  It fixes this issue on my Windows 8.1 PC, but I haven't been able to test on Windows 7.

**Comment by jenatali** [comment] 2017-05-17 19:27
Thanks Jefferson!

Did you try without -simple on Win8.1? I'm curious when PresentMon starts working in normal mode - I've only actually tested on Win10 myself. We should probably figure this out and call it out in documentation, and maybe even consider auto-detecting the OS version.

**Comment by EnzDducharme** [comment] 2017-05-17 19:42
Hello,

I've confirmed that the fix works on Windows 8.1 as intented (using the process_name and delay command lines only). Does not require simple.

It's however unfortunately not the case for Windows 7, which requires -simple to collect data. -process_name now properly detects the application however.

It would naturally be ideal if Windows 7 worked in normal mode but this is definitely extremely helpful for now. Thanks a lot for your efforts so far and the prompt responses.

**Comment by jenatali** [comment] 2017-05-17 19:54
If you're able to provide an [ETL file captured by GPUView's log.cmd](https://msdn.microsoft.com/en-us/library/windows/desktop/jj585574%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) on Windows 7, I can take a look and see what events might not have existed yet. No guarantees on being able to actually provide useful information, but I might be able to automatically fall back to simple processing if I can detect that I'm looking at Win7 events.

**Comment by jdm3** [comment] 2017-07-25 17:31
This should be fixed in the latest version: https://github.com/GameTechDev/PresentMon/releases/tag/v1.2.0

**Closed by jdm3** 2017-07-25 17:31 UTC
