### ISSUE TITLE
Selecting adapter NVIDIA GeForce GTX 970, overlay only reports "basic" telemetry (dual dGPU desktop)

### ISSUE THREAD

**Issue by tim-rex** [GameTechDev/PresentMon#256] opened 2024-06-20 23:53 UTC
I have a dual GPU desktop.
I can capture just fine when I explicitly select the _Radeon RX 580 Series_ device, for any set of metrics (regardless of which GPU is being targeted by the application)

If I switch to capture from the _NVIDIA GeForce GTX 970_ it **appears** I can only capture the "basic" preset.
Switching to any other capture profile at runtime has no effect (basic capture continues to be rendered in the overlay).

If I attempt to restart a capture in any mode other than "basic", no overlay is presented _until_ I revert to "basic"
No change between windowed mode or overlay mode

**However**, a capture CSV report seems to suggest it is capturing, it's just the overlay that is not presented
[pmcap-DX12_fullscreen_portrait_repro.exe-240621-094923.csv](https://github.com/user-attachments/files/15921179/pmcap-DX12_fullscreen_portrait_repro.exe-240621-094923.csv)
[pmcap-DX12_fullscreen_portrait_repro.exe-240621-094923-stats.csv](https://github.com/user-attachments/files/15921180/pmcap-DX12_fullscreen_portrait_repro.exe-240621-094923-stats.csv)

Side question: Is it expected that I should be able to capture using the AMD device, for an application targeting the nVidia device? And should such metrics be considered reliable? (this seems to work, regardless of which device is considered the 'primary' desktop device)

DxDiag report attached if at all helpful
[DxDiag.txt](https://github.com/user-attachments/files/15921155/DxDiag.txt)

**Comment by planetchili** [comment] 2024-07-17 23:46
Hi, thanks for your feedback. Could we get a few points of clarification?

You mention when you switch "from the NVIDIA GeForce GTX 970" (to?), you can only capture the basic preset?
You also mention "a capture CSV report seems to suggest it is capturing".

Just to clarify, is the issue relating to "Capture" (i.e. generating the CSV file), or related to the realtime overlay?

**Comment by tim-rex** [comment] 2024-07-18 03:22
> You mention when you switch "from the NVIDIA GeForce GTX 970" (to?), you can only capture the basic preset?

Apologies for not being clear.
I simply meant, "when capturing the NVIDIA GeForce GTX 970" it will only capture the basic preset.  Changing to other presets (or custom) has no effect


> You also mention "a capture CSV report seems to suggest it is capturing".
> Just to clarify, is the issue relating to "Capture" (i.e. generating the CSV file), or related to the realtime overlay?

The issue is related only to the realtime overlay.
The attached CSV report confirms all stats are being measured

**Comment by planetchili** [comment] 2024-07-19 07:32
Thank you for the clarification. The Basic preset has 1 graph widget displaying Frame Time, whereas the other presets each have a graph displaying FPS metrics as their 1st graph widget. Can you confirm that the graph is only displaying Frame Time no matter what preset is being selected?

**Comment by tim-rex** [comment] 2024-07-23 23:42
Apologies for the delay

I can confirm, the the basic present graph widget displays without issue. Other presets will continue to only display the basic preset when the nVidia GPU adapter is selected

See attached demonstration
![presentmon_overlay_nvidia](https://github.com/user-attachments/assets/cc513d70-3603-436a-b7f5-3ec896200990)

**Comment by planetchili** [comment] 2024-07-25 04:36
Thank you for your continued help! We can reproduce the issue reliably now and we have a good idea about the root cause. We will have a fix for this in an upcoming release, either 2.1.1 due within a week or so, or if it doesn't make it into that release, the one after (2.1.2 or 2.2).

**Closed** 2024-08-05 18:55 UTC
Labels: bug, PresentMon-CaptureApplication
