### ISSUE TITLE
"Displayed fps" shows a much larger value

### ISSUE THREAD

**Issue by subkitajima** [GameTechDev/PresentMon#54] opened 2018-11-22 08:04 UTC
I use PresentMon 1.3.1 which customized to output the console display to a log file, built it on Win32 and used it.
While checking "displayed fps" with my own play player sometimes it may show a much higher value than the frame rate of the content. For example, it shows a value exceeding 200 fps with contents of 59.94 fps. And The display refresh rate is 59 Hz.
Under what conditions can "displayed fps" become a large value?

**Comment by JeffersonMontgomery-Intel** [comment] 2018-11-26 19:10
Applications can present faster than the display refresh rate if they are not (implicitly or explicitly) locked to vsync.

How are you calculating "displayed fps"?  If you are averaging MsBetweenDisplayChange across multiple presents before inverting, make sure you are properly discounting dropped frames (which will have MsBetweenDisplayChange of zero) which could also give you an incorrect value.

**Comment by subkitajima** [comment] 2018-11-27 01:45
"displayed fps" is an item to output in the PresentMon's console window.
It is a value calculated by SwapChainData.Cpp, SwapChainData :: ComputeDisplayedFps function, not part I customized.
Does your reply mean I have to change the calculation of SwapChainData :: ComputeDisplayedFps?

**Comment by subkitajima** [comment] 2018-11-27 02:38
I'd like to check about "displayed fps".
I am using PresentMon 1.3.1 with my own video player application set to "process_name" parameter.
Is "displayed fps" the frame rate of video playback?

**Comment by JeffersonMontgomery-Intel** [comment] 2018-11-27 18:04
Thank-you for the clarification.

First of all, it does look like there's an error in the calculation for "displayed fps" where it is showing the CPU time between displayed frame Present calls, instead of the actual displayed time.  Fix for that is below and I'll include in next release (copy ComputeFps() and change `QpcTime` to `ScreenTime`):

```c++
double SwapChainData::ComputeDisplayedFps(uint64_t qpcFreq) const
{
    if (mDisplayedPresentHistory.size() < 2) {
        return 0.0;
    }
    auto start = mDisplayedPresentHistory.front().ScreenTime;
    auto end = mDisplayedPresentHistory.back().ScreenTime;
    auto count = mDisplayedPresentHistory.size() - 1;

    double deltaT = double(end - start) / qpcFreq;
    return count / deltaT;
}
```

However, I think that would only result in a small error and you should still be seeing something close to the refresh rate.

Is it possible to provide an ETL trace so I can debug this issue?

1. Obtain gpuview by installing the Windows Performance Toolkit
2. Start a capture by running gpuview's log.cmd (e.g., C:\Program Files (x86)\Windows Kits\10\Windows erformance Toolkit\gpuview\log.cmd) as administrator, and end the capture by running log.cmd again. The capture will be output to Merged.etl.  Try to capture for as short as possible to limit .etl size, while still capturing the problem.
3. Test that the Merged.etl capture exhibits the issue you are reporting, by running PresentMon with "-etl_file Merged.etl" (to read from the capture instead of the system).
4. Provide the resulting Merged.etl file.

**Comment by subkitajima** [comment] 2018-11-28 03:01
ETL trace will be provided from tomorrow.
But short capture may be difficult. Because "displayed fps" gets larger because it is confirmed with the log outputted in the movie playback test for a long time (about 12 hours).

A long time (about 12 hours) movie playback test is playing one movie file repeatedly.
In Windows Media Player and VLC Player, "displayed fps" becomes large, it can not be seen in long-time movie playback.It is only my own video player application.
my own video player application is separate from the process using "AxWindowsMediaPlayer" and the GUI process.
A process that uses "AxWindowsMediaPlayer" is started each time one movie file is played, and the process ends with the end of playback.
"displayed fps" has a large value at the start of playback of movie files. But it is not every time.

**Comment by subkitajima** [comment] 2018-11-29 08:55
I played movie file for 1 hour, collected ETL trace and checked whether it is a big frame rate, but it has not happened so far.
However, the file size of Merged.etl of about 1 hour is about 38 GB. Is it possible to upload to the your shared area there?

**Comment by subkitajima** [comment] 2018-12-04 07:19
I use the "displayed fps" value as a test to indicate the frame rate of movie playback.
In SwapChainData :: UpdateSwapChainInfo, 2 seconds or more or 120 or more PresentEvents are deleted from SwapChainData :: mDisplayedPresentHistory.
If the PresentEvent of SwapChainData :: mDisplayedPresentHistory is "equivalent to a playback frame, should the" deltaT "variable in the" displayedFps "calculation in SwapChainData :: ComputeDisplayedFps be MAX_HISTORY_TIME / 1000?

**Comment by JeffersonMontgomery-Intel** [comment] 2019-01-26 00:12
No. `MAX_HISTORY_TIME` is the maximum time window that `ComputeDisplayedFps()` will average over. But the durations of all the displayed presents in `mDisplayedPresentHistory` wont necessarily add up to `MAX_HISTORY_TIME`.

e.g., there might only be two `PresentEvent` instances in `mDisplayedPresentHistory` separated by, say 16ms. The average display time is 16ms ((last-first)/(count-1)).

**Comment by JeffersonMontgomery-Intel** [comment] 2019-08-22 02:51
I'm not able to reproduce this issue.

**Closed by JeffersonMontgomery-Intel** 2019-08-22 02:51 UTC
