### ISSUE TITLE
msvcp140d.dll missing - install 2015/2017 c++ runtimes doesn't help

### ISSUE THREAD

**Issue by eddr** [GameTechDev/PresentMon#39] opened 2017-07-22 10:06 UTC
Any clue?

repeated in several machines with W10 with latest 1703 update. Was working fine before

**Comment by jenatali** [comment] 2017-07-22 13:26
You built a debug build from VS. These binaries are only included with Visual Studio or the remote debugging tools. Either grab one of the pre-built binaries or build the release profile.

**Comment by eddr** [comment] 2017-07-22 13:28
Thanks. Where can I find binaries? the "PresentMonLauncher" had the same problem

**Comment by jenatali** [comment] 2017-07-22 13:32
https://github.com/GameTechDev/PresentMon/releases

**Comment by eddr** [comment] 2017-07-22 13:36
Was not aware of it! Thanks

**Comment by eddr** [comment] 2017-07-25 06:34
Tried the compiled version and indeed I don't get this error again, but still whenever I try to record, I get a general windows error message and no result otherwise.

**Comment by jdm3** [comment] 2017-07-25 14:13
Can you provide any more information, such as what the error message was?

**Comment by eddr** [comment] 2017-07-25 14:41
Thanks, yes, tell me what to add:

1. Now, only a general message: 
http://imgur.com/a/8ZqIu

2. Tried the following versions: The 1.12 release file you referred me to + the one from the PresentMonLauncher package + compiled the sources myself (got a 2.7MB file), but maybe I didn't do it right somehow?

3. Windows 10 1703, latest Nvidia drivers (even removed and reinstalled). No other problems. Every 3D application and game works fine

4. Worked fine till 2-3 months ago. Not sure what changed. That's the third laptop I have problem with (various models and brands, if that matters)

Can I provide somehow more debug info?

**Comment by jenatali** [comment] 2017-07-25 14:44
Right, that's just a general crash. If you're able to compile from source, can you try:
1. Launch Visual Studio as administrator.
2. Run with debugging.

When it crashes, it should break into the debugger and tell you more information about why it's crashing.

**Comment by jdm3** [comment] 2017-07-25 14:45
The next step is probably to determine if the problem is occuring in PresentMon or PresentMonLauncher.  The error seems to indicate the latter.  Could you try running PresentMon from the command line and see if you still see a problem?  If not, I'd suggest we move this issue over to https://github.com/andymanic/PresentMonLauncher

**Comment by eddr** [comment] 2017-07-25 14:50
Oh, you're right, should have checked before - the cmd works fine

**Comment by jdm3** [comment] 2017-07-25 14:55
OK, I'm going to close this issue then -- could you re-post the info from your last three comments, and also probably the version of PresentMon you are using, into a new issue in the PresentMonLauncher project (https://github.com/andymanic/PresentMonLauncher/issues)?

Thanks!

**Closed by jdm3** 2017-07-25 14:55 UTC

**Comment by eddr** [comment] 2017-07-25 15:00
Thanks and apologies for the time, should have tested it:(
Anyway, posted it
