### ISSUE TITLE
Vulkan not recorded?

### ISSUE THREAD

**Issue by eddr** [GameTechDev/PresentMon#31] opened 2017-05-23 19:40 UTC
Hi

Been using PresentMon for quite some time now. It worked well, including for Vulkan.
For some reason, lately I have had problems with recording Vulkan frametimes and now it won't do it at all (work for anything else)

Could it be that some new NV or Windows 10 updates crapped something?
Could it be related to me using an external display with my laptop?

EDIT: I get the files, but they empty or have only the header line

**Comment by jenatali** [comment] 2017-05-23 20:45
I'm assuming you're using the latest versions of PresentMon, yes?

Are you able to capture a trace? If you're able to provide an [ETL file captured by GPUView's log.cmd](https://msdn.microsoft.com/en-us/library/windows/desktop/jj585574%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396), I can debug what's unique about the app or driver causing it to not work properly.

Does it work if you use -simple?

**Comment by eddr** [comment] 2017-05-23 21:59
You're right, it was an old version. It works now
Thanks a lot for your time!

**Comment by jdm3** [comment] 2017-05-23 22:34
Assuming a duplicate of #25.

**Closed by jdm3** 2017-05-23 22:34 UTC
